# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "908d48792ec2c8de4f542c7c395e0f57"
name = "test"
handle = "test-14041"
application_url = "https://turned-producer-symposium-athletic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "au-commense-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://turned-producer-symposium-athletic.trycloudflare.com/auth/callback",
  "https://turned-producer-symposium-athletic.trycloudflare.com/auth/shopify/callback",
  "https://turned-producer-symposium-athletic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
